title: R graphics
description: 'Basic commands with R for plotting '
template:
  repo: r-graphics-template
  name: r-graphics
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
